### ISSUE TITLE
[BUG] Cant insert text of any kind into letters

### ISSUE THREAD

**Issue by IroPlisk** [thedarkcolour/ForestryCE#1]
in the latest version, no matter how many stamps or who you try to send it to (trader station or player), the letter refuses any kind of text. It wont even respond to clicking in the text box itself.

**Comment by thedarkcolour** [comment]
Ah, haven't looked at the mail system yet. I've never used it in game, so bear with me as I go through and fix it

**Comment by thedarkcolour** [comment]
It is now possible to insert text into the letters, not sure if the mail system works yet

**Comment by IroPlisk** [comment]
i can confirm everything 100% works, no issues (singleplayer testing, sending myself mail). I'm going to test it in MP too soon.
