### ISSUE TITLE
Incorrect translation of ru_ru, all item in creative have an English text

### ISSUE THREAD

**Issue by Loker541** [thedarkcolour/ForestryCE#101]
This is what the en_us translation looks like:

{
  "item.forestry.fertilizer_bio": "Compost",
  "item.forestry.fertilizer_compound": "Fertilizer",
  "item.forestry.frame_impregnated": "Impregnated Frame", 
}

This is what the ru_ru translation looks like: 

{

  "item.for.fertilizer_bio.name": "Компост",
  "item.for.fertilizer_compound.name": "Минеральное удобрение",
  "item.for.frame_impregnated.name": "Пропитанная рамка",

} 

After starting the game, the en_us translator file is used

**Comment by Loker541** [comment]
I have corrected the whole translation and added the translation of the forest guide, please consider it, thank you.

https://github.com/thedarkcolour/ForestryMC/compare/dev/1.19.x...Loker541:patch-1?expand=1

**Comment by thedarkcolour** [comment]
You can open the Pull Request yourself :)
