### ISSUE TITLE
Game crashes during world generation with seed 3933010408325374788

### ISSUE THREAD

**Issue by phlopsi** [thedarkcolour/ForestryCE#102]
I used the most recent version of Forestry, Patchouli and Forge for 1.19.2. The title is fairly self-explanatory. I just create a new world, enter the seed and the chunk generation threads crash and I have to manually crash the frozen game, because the main thread is just waiting.

Here's the log:
https://paste.ee/p/ZrEBj

**Comment by thedarkcolour** [comment]
Seems to be a bug with fruit pods.

**Comment by thedarkcolour** [comment]
sick seed btw
