### ISSUE TITLE
[1.0.11]Recipe Override : Log Pile x Log Wood

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#104]
The recipe for the Log pile now overrides the vanilla Decorative Wood blocks requiring additional mods such as Polymorph to access the vanilla recipe

4x Wood in any grid

**Comment by thedarkcolour** [comment]
Whoops. In the meantime, though, you don't need polymorph—you can use the Worktable to get around duplicate recipes.
