### ISSUE TITLE
Lack config to disable bronze

### ISSUE THREAD

**Issue by SigmaFlame** [thedarkcolour/ForestryCE#109]
Lack config to disable bronze crafting recipe.
There are a lot of mods that allow make bronze harder than just put tin and copper inside the crafting table.
Older Forestry mod has this option that was removed in the 1.19+ version.
Thanks in advance.

**Comment by thedarkcolour** [comment]
In newer Minecraft versions, recipes are added with datapacks. There is no need for config options anymore, you can remove them yourself with a datapack, KubeJS, or CraftTweaker.
