### ISSUE TITLE
[1.0.14] Savannah Hives use older texture

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#115]
![2024-11-16_23 52 10](https://github.com/user-attachments/assets/b21581b0-43ba-4514-b45a-0bcd18af85cb)

New hive textures appear to have missed Savannah

**Comment by thedarkcolour** [comment]
Got it. The new textures were originally designed for the 1.16 WIP Forestry by Nedelosk, but Savanna bees were added in community edition.

**Comment by thedarkcolour** [comment]
Fixed in 1.20.1
