### ISSUE TITLE
cant connect to server

### ISSUE THREAD

**Issue by TerminalHash** [thedarkcolour/ForestryCE#130]
client with Forge 47.3.0 and only Patchouli + ForestryCE cant connect to server, throwing constantly one error without any information, what caused it:
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because "p_130056_" is null`

tried with 2.0.0 and 2.0.1 versions.

## Logs
Client:
[latest.log](https://github.com/user-attachments/files/18220170/latest.log)
[debug.log](https://github.com/user-attachments/files/18220171/debug.log)

Server:
[latest.log](https://github.com/user-attachments/files/18220172/latest.log)
[debug.log](https://github.com/user-attachments/files/18220174/debug.log)

**Comment by Dandelion1608** [comment]
I get exactly the same message on my update testing pack, but does work in solo
![image](https://github.com/user-attachments/assets/673eb209-966b-4c19-b3a6-373bad64e2cb)

Client log:
[latest.log](https://github.com/user-attachments/files/18220268/latest.log)

Server:
[debug.log](https://github.com/user-attachments/files/18220269/debug.log)
[latest.log](https://github.com/user-attachments/files/18220271/latest.log)

![image](https://github.com/user-attachments/assets/29ab4b77-ca02-4bf9-803d-a3b05702b803)
