### ISSUE TITLE
[CRASH][BUG] Can't use fluid container items on any block/machine with a fluid container within it/fluid capability

### ISSUE THREAD

**Issue by IroPlisk** [thedarkcolour/ForestryCE#4]
When using any fluid container item on blocks like the carpenter (which have a fluid inventory), the game crashes. This Happens with ANY fluid container item, such as mekanism tanks, pneumaticraft tanks, vanilla buckets. HOWEVER the fluid can be inputted/outputted out of the block (carpenter/squeezer) by putting the liquid container inside the block's gui output.

Steps to replicate the crash:
1) place down a carpenter
2) use a tank/bucket/anything that contains or can contain a fluid (for example, try inserting in a bucket of water)
3) right click with the container in hand on the carpenter
The GUI way to input and output the fluids in the blocks works like a charm, only this "quick way" crashes.

Here i'll attatch the crash log:

[latest.log](https://github.com/user-attachments/files/15838478/latest.log)

**Comment by thedarkcolour** [comment]
Fixed in #5
