### ISSUE TITLE
[1.0.3] Rare Combs from Apiarist Hut Chests have no Centrifuge uses

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#42]
Some Combs obtained from chests in the village Apiraist huts will not Centrifuge

Tested Combs:
* Darkened
* Reddened
* Omega

these seem to come from an FTB Exclusive Family of bees according to Google

> The Darkened Bee is a bee added by [Forestry](https://ftbwiki.org/Forestry) which is only breedable in the [Feed The Beast Retro SSP Pack](https://ftbwiki.org/Feed_The_Beast_Retro_SSP_Pack) and SMP Pack. For these Retro Packs, a special version of Forestry was designed that allowed for this bee (and the two related species, the [Reddened Bee](https://ftbwiki.org/Reddened_Bee) and the [Omega Bee](https://ftbwiki.org/Omega_Bee)) to be bred.

> Darkened Bees were intended to link in with Equivalent Exchange 2, the older version of Equivalent Exchange, and use components from that mod in the process of breeding.

> Darkened Bees can still be obtained via the /givedrone and /giveprincess commands in the non-FTB versions of Forestry, as can Reddened and Omega bees. However, this is the only method of obtaining them in all packs except Retro SSP/SMP.

[https://ftbwiki.org/Darkened_Bee_(Forestry)](url)

**Comment by thedarkcolour** [comment]
I will remove these in the 1.20 version, I don't want to break existing worlds
