### ISSUE TITLE
the managed farm only plants from it 2nd row

### ISSUE THREAD

**Issue by JustGuy48** [thedarkcolour/ForestryCE#43]
the managed farm only plant from its 2nd row of seeds/plants and does not make a full farm, instead it looks like this
![image](https://github.com/user-attachments/assets/397a6f98-269e-49fb-b2b6-4fc62ea715c9)
(left side wheat and right side potatos)
when this is its input
![image](https://github.com/user-attachments/assets/539c2c29-d0e4-43d4-8380-c87460723c21)

and when seeds enter the top right part of the output slots it will replant them in the first/top row of empty farmland in the first picture, but if it has something that cannot be planted in that slot it just leaves the empty farmland empty
* this problem might happen with the bottom empty farmland too from what saw though i dont know from which empty slot in the output of the farm machine

**Comment by thedarkcolour** [comment]
Looks like it's only planting from the bottom two slots
