### ISSUE TITLE
[1.0.4] Database can be crafted with a Plum, Royal Jelly or a regular chest

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#50]
According to JEI/EMI the Database block can be crafted with either a Plum, a Royal Jelly or a Chest in the Bottom Center grid Square

unclear if this is by design but seems too varied to be the case, why a plum?

![image](https://github.com/user-attachments/assets/db2a6eaf-d36d-457f-994a-311913051bf2)
![image](https://github.com/user-attachments/assets/c3598708-fe3e-472c-afc3-8dc8207160c0)
![image](https://github.com/user-attachments/assets/d4474fc0-e681-4e51-b31a-f2f735c32a54)
![image](https://github.com/user-attachments/assets/4fc797b7-df20-450b-8d1e-472572c559f0)

**Comment by thedarkcolour** [comment]
This was intentional. It was written by the same person who originally wrote the code for the database.

**Comment by Dandelion1608** [comment]
Ah that's fair enough then, it just seemed a bit weird to be a chest, royal jelly or specifically a Plum

I'll close this as it's not an issue
