### ISSUE TITLE
Bee tags for better item sorting

### ISSUE THREAD

**Issue by Peatral** [thedarkcolour/ForestryCE#55]
I think it would be great if there were tags for the bees.
One general like `forestry:bee`, and `forestry:queen`, `forestry:drone` and `forestry:princess` under it.
(`bee` just has the tags for `queen`, `drone`, and `princess` and no items itself, while these 3 each have all the different bee items below them)

This could massively help with automating farms and sorting out the different bees.

I could probably even implement the datagen myself.

**Comment by Peatral** [comment]
Oh lol i just saw that the tags were already added, just not in the latest release. As there is only one item per bee, my solution would probably be overkill, as each of the tags would only contain one item (but would make it easier for other mods to add custom bee items, although i wouldnt know why anybody would want this)

\+ I forgot about the larvae, rookie mistake

**Comment by thedarkcolour** [comment]
I'm not going to add the princess/drone/queen tags because the life stages are hardcoded to only be one item. But yes, I have already added a bee tag, mostly for quest book purposes.
