### ISSUE TITLE
[1.0.5] Fruit Juice requires specific fruit

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#59]
Fruit Juice requires specific fruits in the squeezer and does not use the fruit tag,

I understand this may be due to the fact cherries, walnuts and chestnuts are used to make seed-oil instead of fruit juice - could these have the "Forge:fruits" tag replaced with "Forge:nuts" - I appreciate cherries aren't actually nuts however mechanically speaking within forestry they are closer to nuts than fruit,

this would add further mod compatability - that said, with Forge Tags leaving soon anyway this suggestion may be redundant anyway

**Comment by thedarkcolour** [comment]
I forgot to replace usages of the fruit items with tags. I'll have this in next update.

**Comment by Peatral** [comment]
I'm not quite sure but didn't different fruits give different amounts of juice? (But of course I would prefer the usage of tags)

**Comment by thedarkcolour** [comment]
In that case I could replace those fruits with their specific tags, like `forge:fruits/lemon` for example
