### ISSUE TITLE
[1.0.5] Unreplicatable Carpenter CTD

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#60]
Every so often while in multiplayer the Carpenter block will throw out a client side CTD, I am unclear if this is actually caused by forestry. However standard troubleshooting (remove everything else and use only forestry) proves impossible due to the fact that simply opening a local world and using the carpenter in exactly the same way (survival sourced materials etc) does not replicate the CTD - further to this, upon successfully using the Carpenter in Solo play, the fault in multi player appears to be resolved

Issue raised more for awareness than fix expectation

[Crash Report](https://gist.github.com/Dandelion1608/9e9619c5b6cb4b749ce8aeb8eec81704)

**Comment by thedarkcolour** [comment]
Seems to be the same issue as #57 but I'll keep this open since it contains useful insight for reproducing the issue
