### ISSUE TITLE
[1.0.5/6] Fruits don't drop on decay

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#61]
Unclear if intentional design behaviour

Fruiting Tree leaves such as Hill Cherry and Lemon do not drop the fruit on leaves decay and fruit must be manually harvested - 
previously chopping down a tree would harvest all ripe fruits as the leaf blocks decayed and not just on right-click

if this is intentional would it be possible to add a config option to toggle harvest on decay?

**Comment by thedarkcolour** [comment]
Seems like saplings aren't dropping either.

**Comment by Dandelion1608** [comment]
Using Tree Harvester/Fast leaf decay I have had saplings drop from trees like the Silver Lime in 1.0.6, haven't tried with a fruit tree yet

Forestry saplings don't seem to replant woth tree harvester but I don't think that's a forestry bug

**Comment by Dandelion1608** [comment]
Confirmed - with TH/FLD Saplings do drop from cherry trees, 

i believe they were setup to be a rarer drop initially to promote the use of the Grafter?

**Comment by thedarkcolour** [comment]
Try modifying the genome of your saplings so that the tree places "forestry:leaves" instead of a "default" leaves block. Those leaves do not drop saplings.

You can modify by crossbreeding or using a command

**Comment by Dandelion1608** [comment]
without checking each leaves block individually it looks like the sugar maple leaves default to forestry:leaves, as do the Hill Cherry, both drop between 5 and 16 saplings for me, as does the forestry genomed Jungle tree which without crossbreeding or other shenanigans seems to default to a single block wide and will not grow as a 2x2 variant

**Comment by Dandelion1608** [comment]
Tested with an analyzed Wenge too, this dropped a total 31 saplings with Tree Harvesters Fast Leaf decay enabled, 

Manually Breaking the leaves on a hill cherry has also yielded saplings - not as many it seems as natural decay but they do still drop
