### ISSUE TITLE
[1.0.5] Apirary in the nether registering as Normal/Normal [Mod Compat]

### ISSUE THREAD

**Issue by Dandelion1608** [thedarkcolour/ForestryCE#65]
Probably A mod/datapack compatability error

Incendium Biomes such as "Infernal Dunes" shows as Normal/Normal not Hellish

Will look into creating a datapack for this

**Comment by Dandelion1608** [comment]
Incendium Compat Datapack - unsure where else to upload this
[forestryxincendium.zip](https://github.com/user-attachments/files/16742743/forestryxincendium.zip)

**Comment by thedarkcolour** [comment]
I'm going to change the hellish tag to include biomes tagged under `#minecraft:is_nether`. Hopefully that solves the issue.
