### ISSUE TITLE
Make Cocoa combs drop honey

### ISSUE THREAD

**Issue by thedarkcolour** [thedarkcolour/ForestryCE#70]
A suggestion was made in Discord to have the Cocoa combs drop honey drops so that the Heroic line isn't as useless (Valiant, Steadfast, Heroic)

**Comment by Dandelion1608** [comment]
I always thought the point of the heoric line was more about the fact they were defensive bees rather than producers

**Comment by thedarkcolour** [comment]
Ahhh right.
