### ISSUE TITLE
Sky is always obstructed for hives in the end

### ISSUE THREAD

**Issue by thedarkcolour** [thedarkcolour/ForestryCE#71]
In previous versions of Minecraft, whether a block could see the sky or not was determined using the block heightmap. Now, Minecraft uses the sky light to determine if a block can see the sky. However, there is no sky light in The End, which means hives that aren't cave-dwelling can't work anywhere in The End.

**Comment by EnderiumSmith** [comment]
If youre changing how sky access is determined, translucent blocks like leaves or water should also not block it unless theyre thick enough.

**Comment by thedarkcolour** [comment]
Fixed in #85
