### ISSUE TITLE
Savannah bee prototype

### ISSUE THREAD

**Issue by EnderiumSmith** [thedarkcolour/ForestryCE#76]
In order to fill the climate table, an additional bee line native to the savannah is needed, also present in sparse jungles.
Colors would be orangeish, light blue like clay and brownish orange with glint.
![Screenshot from 2024-08-30 01-35-48](https://github.com/user-attachments/assets/24767f23-1b75-4bb2-9813-65c08f70bd10)
![Screenshot from 2024-08-30 01-37-41](https://github.com/user-attachments/assets/56332582-33fb-49f6-bf89-2ffc54ee5951)
Description: A subspecies of ground nesting bees, commonly found in warmer climates -beekeeping 101
They produce Parched Combs with Red Sand as a speciality
Sifter effect: very slowly removes the clays from surrounding blocks. Soil type blocks become Coarse Dirt, Mud type blocks become Sand and Soul Soil becomes Soul Sand.
They use gourds as flowers since those are more common in those climates than flowers, and every bee line has a distinct flower.
Similar to how Marshy are bred with nobles, Savannah are bred with diligent
![Screenshot from 2024-08-30 01-36-07](https://github.com/user-attachments/assets/5ccc046a-4ce8-42a2-b6d7-c8096fe96f8b)
Description: These bees endure long periods of drought by incorporating increasing amounts of waterproof clays into their nests -beekeeping 101
They produce Kaolin Combs, which make clay and honey drops with no wax, as well as Red Sand as a speciality
The final bee is bred with Savannah and Argile, but only on the peaks of shattered savannah biomes
![Screenshot from 2024-08-30 01-36-15](https://github.com/user-attachments/assets/291c96fd-1193-4097-9c11-9f1a7b45d9eb)
Description: Look, Simba: Everything the bees touch is our kingdom. -Mufasa
They produce Kaolin Combs and Mellow Combs as a speciality
Hakuna Matata effect: Lowers incoming damage by a flat -5 and sets mob follow range to 0. If damage exceeds 5 the effect is replaced by the Matata effect for both target and attacker, which prevents the Hakuna from being reapplied until it wears off.

**Comment by thedarkcolour** [comment]
## Savanna
- What if Savanna bees had a certain chance of spawning with the Aggressive effect? 
- The species should probably use "Savanna" by default as that is the American English spelling. There would be a separate translation for UK/Canadian English where it's spelled "Savannah."
- Why is the species nocturnal?
## Argil
Looks good.
## Pride
- Could the lifespan be "Shorter" instead of "Short?" More variation in the genetics throughout the line would be nice

Overall looks sick. Do you want to code these species yourself and submit a Pull Request, or would you like me to do it?

**Comment by EnderiumSmith** [comment]
yes, aggressive its probably better fit for first stage since they dont yet make clay
its nocturnal because its really hot in savannas and the desert is nocturnal too
bee lines like marshy and wintry keep their lifespan the same so it fits the pattern. if anything it should go up to shortened
its better you code them since i dont have the IDE set up for that

**Comment by thedarkcolour** [comment]
Alright 👍

**Comment by thedarkcolour** [comment]
Implemented in #85
